name: Depoloy Backend on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SECRET_KEY }}
          script: |
            cd ~/akar-event-management-system/backend && \
            git pull origin main && \
            pm2 stop nextjs-app && \
            pkill -f 'next build' || true && \
            npm install && \
            rm -rf .next && \
            npm run build && \
            pm2 start npm --name nextjs-app -- run start && \
            pm2 save
